// Autogenerated portfolio data containing all client videography categories and photography event coverage
export interface VideoProject {
  id: string;
  title: string;
  category: string;
  categorySlug: string;
  client: string;
  year: string;
  driveId: string;
  folderId?: string;
  thumbnail: string;
  tagline: string;
  featured?: boolean;
  isFullLengthBanner?: boolean;
  isTallLength?: boolean;
  gridSpan: string;
  minHeight: string;
  aspectClass: string;
  masonryHeight: string;
}

export const videoProjects: VideoProject[] = [
  {
    "id": "vid-1",
    "title": "INNOWIZE — Next-Gen AI Visuals & Synth",
    "category": "AI Videos",
    "categorySlug": "ai-videos",
    "client": "Innowize AI Labs",
    "year": "2024",
    "driveId": "1p_uVBDvay8eC5QuxgE7aH3WQV_coFDwr",
    "folderId": "1W6c8Gq3o3I9U8vTuwF2GpxOAAxz9jJh7",
    "thumbnail": "https://lh3.googleusercontent.com/d/1p_uVBDvay8eC5QuxgE7aH3WQV_coFDwr=w1200",
    "tagline": "Cutting-edge artificial intelligence video generation, neural motion graphics, and algorithmic storytelling.",
    "featured": true,
    "isFullLengthBanner": true,
    "gridSpan": "col-span-1 md:col-span-2 lg:col-span-3 xl:col-span-4",
    "minHeight": "min-h-[460px] lg:min-h-[540px]",
    "aspectClass": "aspect-[21/9]",
    "masonryHeight": "h-[500px]"
  },
  {
    "id": "vid-2",
    "title": "AfterLife Music Festival — Official Promo",
    "category": "Events",
    "categorySlug": "events",
    "client": "Afterlife Asia",
    "year": "2023",
    "driveId": "1bcJgpKoTQrkOfIXG9K7GQ_sKtTGllZ_y",
    "folderId": "1L8nzrObb9wak6BpAYiGDDMUrskbr7-8D",
    "thumbnail": "https://lh3.googleusercontent.com/d/1bcJgpKoTQrkOfIXG9K7GQ_sKtTGllZ_y=w1200",
    "tagline": "Mesmerizing melodic techno rhythms, monumentally scaled stage lighting, and transcendent stadium crowds.",
    "featured": true,
    "isFullLengthBanner": true,
    "gridSpan": "col-span-1 md:col-span-2 lg:col-span-3 xl:col-span-4",
    "minHeight": "min-h-[460px] lg:min-h-[540px]",
    "aspectClass": "aspect-[21/9]",
    "masonryHeight": "h-[520px]"
  },
  {
    "id": "vid-3",
    "title": "Alaxis Medical Aesthetics — Beauty & Radiance",
    "category": "Brand Story",
    "categorySlug": "brand-story",
    "client": "Alaxis Aesthetic Clinic",
    "year": "2024",
    "driveId": "1TTQEAe3FdxFGb9KtTIIfFWZX43QlFNaL",
    "folderId": "1-lbbuQEsutdT25V_-wtnBFvlGKVtDceT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1TTQEAe3FdxFGb9KtTIIfFWZX43QlFNaL=w1200",
    "tagline": "High-fashion 9:16 vertical aesthetic cinematography tailored for luxury wellness and dermatological elegance.",
    "isTallLength": true,
    "gridSpan": "col-span-1 xl:row-span-2",
    "minHeight": "min-h-[620px] lg:min-h-[700px]",
    "aspectClass": "aspect-[9/16]",
    "masonryHeight": "h-[680px]"
  },
  {
    "id": "vid-4",
    "title": "Achieve Spine & Orthopaedics — Patient Care",
    "category": "Brand Story",
    "categorySlug": "brand-story",
    "client": "Achieve Spine & Orthopaedics",
    "year": "2024",
    "driveId": "1Uf00_w-QtVPy7Q8nCnLzNwW4MnU5YdNf",
    "folderId": "1-lbbuQEsutdT25V_-wtnBFvlGKVtDceT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Uf00_w-QtVPy7Q8nCnLzNwW4MnU5YdNf=w1200",
    "tagline": "An intimate surgical brand narrative highlighting world-class orthopedic precision, patient recovery, and surgical expertise.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px] lg:min-h-[420px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[390px]",
    "featured": true
  },
  {
    "id": "vid-5",
    "title": "Accelerate 2024 — Heroes of Digital x Google",
    "category": "Events",
    "categorySlug": "events",
    "client": "Heroes of Digital & Google",
    "year": "2024",
    "driveId": "10eDuJvKA90GTqpQQ9u98BT-oDocS8zD9",
    "folderId": "1L8nzrObb9wak6BpAYiGDDMUrskbr7-8D",
    "thumbnail": "https://lh3.googleusercontent.com/d/10eDuJvKA90GTqpQQ9u98BT-oDocS8zD9=w1200",
    "tagline": "Explosive technology summit recap with high-octane stage cinematography, executive keynotes, and thought leadership.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[400px]",
    "featured": true
  },
  {
    "id": "vid-6",
    "title": "HiveBotics — Abluo Autonomous Cleaning Robotics",
    "category": "Product & Service",
    "categorySlug": "product-service",
    "client": "HiveBotics Robotics",
    "year": "2024",
    "driveId": "1l2wnGZ4GhEKXTNQgYw9BmSdqQO88l7UV",
    "folderId": "1zdQcNTS0XbCaogeq1aeJpPNiWGE52iea",
    "thumbnail": "https://lh3.googleusercontent.com/d/1l2wnGZ4GhEKXTNQgYw9BmSdqQO88l7UV=w1200",
    "tagline": "Sleek industrial product film unveiling groundbreaking robotics engineering and AI navigation automation.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-[4/3]",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-7",
    "title": "CG Property Group — Founders’ Story",
    "category": "Brand Story",
    "categorySlug": "brand-story",
    "client": "CG Property Group",
    "year": "2024",
    "driveId": "163RNjt3l0yvUOX4V-S2xYWgRmkMAk-oL",
    "folderId": "1-lbbuQEsutdT25V_-wtnBFvlGKVtDceT",
    "thumbnail": "https://lh3.googleusercontent.com/d/163RNjt3l0yvUOX4V-S2xYWgRmkMAk-oL=w1200",
    "tagline": "The journey of real estate pioneers transforming premier urban spaces with architectural vision and legacy commitment.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[440px] lg:min-h-[480px]",
    "aspectClass": "aspect-[3/4]",
    "masonryHeight": "h-[460px]"
  },
  {
    "id": "vid-8",
    "title": "Staking Circle — Session 1: Future of Proof-of-Stake",
    "category": "Panel Discussions",
    "categorySlug": "panel-discussions",
    "client": "Staking Circle International",
    "year": "2024",
    "driveId": "1xlrAh68tzv6MYBVwV7rto_UgWj5sUU2G",
    "folderId": "1EbBKhvHixExHkki6Vhn-os1Uc4BNfyKS",
    "thumbnail": "https://lh3.googleusercontent.com/d/1xlrAh68tzv6MYBVwV7rto_UgWj5sUU2G=w1200",
    "tagline": "In-depth technical panel discussion exploring validator architecture, restaking mechanics, and enterprise risk management.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[390px]"
  },
  {
    "id": "vid-9",
    "title": "Staking Circle — Session 2: Institutional Adoption",
    "category": "Panel Discussions",
    "categorySlug": "panel-discussions",
    "client": "Staking Circle International",
    "year": "2024",
    "driveId": "1T_fIevdFfJgtM875JDoXFkssQ3Z3cNK7",
    "folderId": "1EbBKhvHixExHkki6Vhn-os1Uc4BNfyKS",
    "thumbnail": "https://lh3.googleusercontent.com/d/1T_fIevdFfJgtM875JDoXFkssQ3Z3cNK7=w1200",
    "tagline": "World-class blockchain executives debating protocol scalability, liquidity staking derivatives, and regulatory compliance.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[390px]"
  },
  {
    "id": "vid-10",
    "title": "Stanford Club of Singapore — Alumni Annual Gala",
    "category": "Events",
    "categorySlug": "events",
    "client": "Stanford University Alumni Association",
    "year": "2023",
    "driveId": "1K7I_avqYCJM5nDRAgtFCugFM1QCu4DtT",
    "folderId": "1L8nzrObb9wak6BpAYiGDDMUrskbr7-8D",
    "thumbnail": "https://lh3.googleusercontent.com/d/1K7I_avqYCJM5nDRAgtFCugFM1QCu4DtT=w1200",
    "tagline": "Sophisticated evening celebrating visionary alumni leaders, collegiate traditions, and lifelong Stanford bonds.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-[4/3]",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-11",
    "title": "Gotbit Web3 Global Liquidity Summit",
    "category": "Events",
    "categorySlug": "events",
    "client": "Gotbit Hedge Fund",
    "year": "2024",
    "driveId": "1vDtDuNigLXmwyKEjwtZeXAA-cHXDxKSJ",
    "folderId": "1L8nzrObb9wak6BpAYiGDDMUrskbr7-8D",
    "thumbnail": "https://lh3.googleusercontent.com/d/1vDtDuNigLXmwyKEjwtZeXAA-cHXDxKSJ=w1200",
    "tagline": "Global decentralized finance conference capturing crypto institutional leaders and networking dynamics.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-square",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-12",
    "title": "Diano x Carousell — Marketplace Lifestyle Film",
    "category": "Brand Story",
    "categorySlug": "brand-story",
    "client": "Carousell & Diano",
    "year": "2024",
    "driveId": "1h5VmTProRFefgdBU1YmxcnxogF2WFj26",
    "folderId": "1-lbbuQEsutdT25V_-wtnBFvlGKVtDceT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1h5VmTProRFefgdBU1YmxcnxogF2WFj26=w1200",
    "tagline": "High-energy commerce narrative spotlighting creative entrepreneurship and preloved culture across Southeast Asia.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-square",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-13",
    "title": "SOS Clinic — Healthcare Innovation & Care",
    "category": "Brand Story",
    "categorySlug": "brand-story",
    "client": "SOS International Clinic",
    "year": "2024",
    "driveId": "1dy8tqXquKgsLdEOEd_c-_fuQj1VwqQi1",
    "folderId": "1-lbbuQEsutdT25V_-wtnBFvlGKVtDceT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1dy8tqXquKgsLdEOEd_c-_fuQj1VwqQi1=w1200",
    "tagline": "Comprehensive medical excellence, state-of-the-art facility showcase, and human-centered compassionate care.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[390px]"
  },
  {
    "id": "vid-14",
    "title": "TKMA — Hydrafacial Vortex Rejuvenation",
    "category": "Product & Service",
    "categorySlug": "product-service",
    "client": "TKMA Aesthetic Dermatology",
    "year": "2024",
    "driveId": "1l53fBHGCJ1pOZg-4xPijLhaOZ4MT3cPg",
    "folderId": "1zdQcNTS0XbCaogeq1aeJpPNiWGE52iea",
    "thumbnail": "https://lh3.googleusercontent.com/d/1l53fBHGCJ1pOZg-4xPijLhaOZ4MT3cPg=w1200",
    "tagline": "Crisp macro cinematography highlighting patented vortex dermal infusion and rejuvenating clinical aesthetic results.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-[4/3]",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-15",
    "title": "CG Property — Client Success & Wealth Story",
    "category": "Testimonials",
    "categorySlug": "testimonials",
    "client": "CG Property Group",
    "year": "2024",
    "driveId": "1-cR8RVQxWaxMf-_JidtrgY3i0acjMfXI",
    "folderId": "1WXWALFZR9L-D_p6WeYLmY0PGbPCxKMGS",
    "thumbnail": "https://lh3.googleusercontent.com/d/1-cR8RVQxWaxMf-_JidtrgY3i0acjMfXI=w1200",
    "tagline": "Authentic, cinematic interviews with high-net-worth investors sharing their seamless property portfolio acquisitions.",
    "gridSpan": "col-span-1",
    "minHeight": "min-h-[360px]",
    "aspectClass": "aspect-square",
    "masonryHeight": "h-[360px]"
  },
  {
    "id": "vid-16",
    "title": "Svenson — Trichology Q&A with Kristina",
    "category": "Testimonials",
    "categorySlug": "testimonials",
    "client": "Svenson Hair Center",
    "year": "2024",
    "driveId": "1LUnj2YoGdC91VyNz-4j1_ASwcqgp73ln",
    "folderId": "1WXWALFZR9L-D_p6WeYLmY0PGbPCxKMGS",
    "thumbnail": "https://lh3.googleusercontent.com/d/1LUnj2YoGdC91VyNz-4j1_ASwcqgp73ln=w1200",
    "tagline": "Candid trichology expert consultation and client transformation journey filmed in intimate studio lighting.",
    "gridSpan": "col-span-1 md:col-span-2",
    "minHeight": "min-h-[380px]",
    "aspectClass": "aspect-[16/9]",
    "masonryHeight": "h-[390px]"
  }
];

// Re-export photo collections for seamless backward compatibility
export { photoCollections } from './photoData';
export type { PhotoItem, PhotoCollection } from './photoData';
